//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 12:14:05 Œß‘O JST 
//


package org.nisshiee.passwordManager.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Db complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Db">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="data" type="{http://www.nisshiee.org/password_manager/xml/3.2.xsd}Data"/>
 *         &lt;element name="markDefs" type="{http://www.nisshiee.org/password_manager/xml/3.2.xsd}MarkDefs" minOccurs="0"/>
 *         &lt;element name="config" type="{http://www.nisshiee.org/password_manager/xml/3.2.xsd}Config" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Db", propOrder = {

})
public class Db {

    @XmlElement(required = true)
    protected Data data;
    protected MarkDefs markDefs;
    protected Config config;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setData(Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the markDefs property.
     * 
     * @return
     *     possible object is
     *     {@link MarkDefs }
     *     
     */
    public MarkDefs getMarkDefs() {
        return markDefs;
    }

    /**
     * Sets the value of the markDefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarkDefs }
     *     
     */
    public void setMarkDefs(MarkDefs value) {
        this.markDefs = value;
    }

    /**
     * Gets the value of the config property.
     * 
     * @return
     *     possible object is
     *     {@link Config }
     *     
     */
    public Config getConfig() {
        return config;
    }

    /**
     * Sets the value of the config property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config }
     *     
     */
    public void setConfig(Config value) {
        this.config = value;
    }

}
