//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 12:14:05 �ߑO JST 
//

package org.nisshiee.passwordManager.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.nisshiee.passwordManager.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Db_QNAME = new QName(
			"http://www.nisshiee.org/password_manager/xml/3.2.xsd", "db");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.nisshiee.passwordManager.xml
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Mark }
	 * 
	 */
	public Mark createMark() {
		return new Mark();
	}

	/**
	 * Create an instance of {@link Service }
	 * 
	 */
	public Service createService() {
		return new Service();
	}

	/**
	 * Create an instance of {@link Data }
	 * 
	 */
	public Data createData() {
		return new Data();
	}

	/**
	 * Create an instance of {@link PMFile }
	 * 
	 */
	public PMFile createPMFile() {
		return new PMFile();
	}

	/**
	 * Create an instance of {@link Db }
	 * 
	 */
	public Db createDb() {
		return new Db();
	}

	/**
	 * Create an instance of {@link Directory }
	 * 
	 */
	public Directory createDirectory() {
		return new Directory();
	}

	/**
	 * Create an instance of {@link PassSetting }
	 * 
	 */
	public PassSetting createPassSetting() {
		return new PassSetting();
	}

	/**
	 * Create an instance of {@link MarkDefs }
	 * 
	 */
	public MarkDefs createMarkDefs() {
		return new MarkDefs();
	}

	/**
	 * Create an instance of {@link Config }
	 * 
	 */
	public Config createConfig() {
		return new Config();
	}

	/**
	 * Create an instance of {@link WordSetting }
	 * 
	 */
	public WordSetting createWordSetting() {
		return new WordSetting();
	}

	/**
	 * Create an instance of {@link Def }
	 * 
	 */
	public Def createDef() {
		return new Def();
	}

	/**
	 * Create an instance of {@link Word }
	 * 
	 */
	public Word createWord() {
		return new Word();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Db }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.nisshiee.org/password_manager/xml/3.2.xsd", name = "db")
	public JAXBElement<Db> createDb(Db value) {
		return new JAXBElement<Db>(_Db_QNAME, Db.class, null, value);
	}

	public static String getXSDVersion() {
		return _Db_QNAME.getNamespaceURI();
	}
}
