//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 12:14:05 Œß‘O JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nisshiee.org/password_manager/xml/3.2.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.nisshiee.passwordManager.xml;
