//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 02:20:33 Œß‘O JST 
//


package org.nisshiee.passwordManager.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PassSetting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PassSetting">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="makePass" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="passLength" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="useLowerCase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="useUpperCase" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="useNumber" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PassSetting")
public class PassSetting {

    @XmlAttribute
    protected Boolean makePass;
    @XmlAttribute
    protected Integer passLength;
    @XmlAttribute
    protected Boolean useLowerCase;
    @XmlAttribute
    protected Boolean useUpperCase;
    @XmlAttribute
    protected Boolean useNumber;

    /**
     * Gets the value of the makePass property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMakePass() {
        return makePass;
    }

    /**
     * Sets the value of the makePass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMakePass(Boolean value) {
        this.makePass = value;
    }

    /**
     * Gets the value of the passLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPassLength() {
        return passLength;
    }

    /**
     * Sets the value of the passLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPassLength(Integer value) {
        this.passLength = value;
    }

    /**
     * Gets the value of the useLowerCase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseLowerCase() {
        return useLowerCase;
    }

    /**
     * Sets the value of the useLowerCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseLowerCase(Boolean value) {
        this.useLowerCase = value;
    }

    /**
     * Gets the value of the useUpperCase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseUpperCase() {
        return useUpperCase;
    }

    /**
     * Sets the value of the useUpperCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseUpperCase(Boolean value) {
        this.useUpperCase = value;
    }

    /**
     * Gets the value of the useNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseNumber() {
        return useNumber;
    }

    /**
     * Sets the value of the useNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseNumber(Boolean value) {
        this.useNumber = value;
    }

}
