//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 01:21:51 Œß‘O JST 
//


package org.nisshiee.passwordManager.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WordSetting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WordSetting">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="passSetting" type="{http://www.nisshiee.org/password_manager/xml/3.2.xsd}PassSetting" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="hidePass" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WordSetting", propOrder = {
    "passSetting"
})
public class WordSetting {

    protected PassSetting passSetting;
    @XmlAttribute
    protected Boolean hidePass;

    /**
     * Gets the value of the passSetting property.
     * 
     * @return
     *     possible object is
     *     {@link PassSetting }
     *     
     */
    public PassSetting getPassSetting() {
        return passSetting;
    }

    /**
     * Sets the value of the passSetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassSetting }
     *     
     */
    public void setPassSetting(PassSetting value) {
        this.passSetting = value;
    }

    /**
     * Gets the value of the hidePass property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHidePass() {
        return hidePass;
    }

    /**
     * Sets the value of the hidePass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHidePass(Boolean value) {
        this.hidePass = value;
    }

}
